import 'package:nakhra/features/shop/models/book_model.dart';
import 'package:nakhra/utils/constants/image_strings.dart';

class DummyData {
  static final List<BookModel> books = [
    BookModel(
      id: '001',
      title: 'Rich Dad Poor Dad',
      authorId: 'Robert T. Kiyosaki',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.richDadPoorDad,
    ),
    BookModel(
      id: '002',
      title: 'The Subtle Art Of Not Giving A Fuck ',
      authorId: 'Mark Manson',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.subtleArtOfNotGivingAFuck,
    ),
    BookModel(
      id: '003',
      title: 'The 48 Laws of Power',
      authorId: 'Robert Greene',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.lawsOfPower,
    ),
    BookModel(
      id: '004',
      title: 'Do It Today',
      authorId: 'Darius Foroux',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.doItToday,
    ),
    BookModel(
      id: '005',
      title: 'Do Epic Shit',
      authorId: 'Ankur Warikoo',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.doEpicShit,
    ),
    BookModel(
      id: '006',
      title: 'Ikigai',
      authorId: 'Hector Garcia',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.ikigai,
    ),
    BookModel(
      id: '007',
      title: 'Surrounded by Idiots',
      authorId: 'Thomas Erikson',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.surroundedByIdiots,
    ),
    BookModel(
      id: '001',
      title: 'Rich Dad Poor Dad',
      authorId: 'Robert T. Kiyosaki',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.richDadPoorDad,
    ),
    BookModel(
      id: '002',
      title: 'The Subtle Art Of Not Giving A Fuck ',
      authorId: 'Mark Manson',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.subtleArtOfNotGivingAFuck,
    ),
    BookModel(
      id: '003',
      title: 'The 48 Laws of Power',
      authorId: 'Robert Greene',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.lawsOfPower,
    ),
    BookModel(
      id: '004',
      title: 'Do It Today',
      authorId: 'Darius Foroux',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.doItToday,
    ),
    BookModel(
      id: '005',
      title: 'Do Epic Shit',
      authorId: 'Ankur Warikoo',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.doEpicShit,
    ),
    BookModel(
      id: '006',
      title: 'Ikigai',
      authorId: 'Hector Garcia',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.ikigai,
    ),
    BookModel(
      id: '007',
      title: 'Surrounded by Idiots',
      authorId: 'Thomas Erikson',
      price: 19.99,
      categoryId: 'Self Help',
      coverImageUrl: ZImages.surroundedByIdiots,
    ),
  ];
}
