name: nakhra
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.4

# ------------ Packages ----------#
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

  #----- Utility Packages----
  http: ^1.6.0
  intl: ^0.20.2
  logger: ^2.6.2
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  lottie: ^3.3.2
  carousel_slider: ^5.1.2

  #------Icons--------
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8



 #-----State Management-----
  get: ^4.7.3
  get_storage: ^2.1.1
  firebase_core: ^4.5.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  google_sign_in: ^6.3.0
  internet_connection_checker_plus: ^2.9.1+2
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0

 #-----Product Specific



 #------Packages End----#



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^6.0.0





flutter:
  uses-material-design: true

  #------Local Assets------
  
  assets: 
   #env file path
    - .env
    # - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/animations/onboardingAnimation/


#--------Local Fonts------

  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800